### ISSUE TITLE
Should we decode it as well? (UTF-32 / UCS-4)

### ISSUE THREAD

**Issue by KWillets** [lemire/fastvalidate-utf-8#13]
We've already figured out a lot about the structure of the stream and what each byte is.  Producing the 32-bit value of each encoded integer seems within reach.

What I'm thinking is that we can produce the 1-4 byte values in place by packing bits right, and then expand them to 32-bit alignment via a shuffle table.  carried_continuations has the distance of each byte from the end, so we can mask off each case and shift/mask to the next lower byte.  

The rightward shift is simply twice the distance from the end: 0,2,4 or 6.  The mask is 0x3F for continuations, or the lower 3-5 bits for initials -- it can be looked up from hibits.

There are some remaining questions about how to continue the iteration after consuming a variable number of bytes (4-16) from the register, and bridging across registers.

And, the bytes are actually reversed from little-endian, but the shuffle can fix that up.

**Comment by lemire** [comment]
> Producing the 32-bit value of each encoded integer seems within reach.

Of course!

**Comment by lemire** [comment]
All I could find on the topic is this paper...

* Robert D. Cameron. 2008. [A case study in SIMD text processing with parallel bit streams: UTF-8 to UTF-16 transcoding](http://www.cs.sfu.ca/people/Faculty/cameron/ppopp074-cameron.pdf). In Proceedings of the 13th ACM SIGPLAN Symposium on Principles and practice of parallel programming (PPoPP '08). ACM, New York, NY, USA, 91-98. 

And that's not quite it.

**Comment by lemire** [comment]
And, of course, there is this transcoder to UTF-16...

https://woboq.com/blog/utf-8-processing-using-simd.html

https://github.com/woboq/utf8sse4/blob/master/fromutf8-sse.cc


Again, not quite the same thing...

**Comment by lemire** [comment]
@KWillets  +1

**Comment by KWillets** [comment]
https://gist.github.com/KWillets/8a633c0b5774a6d77bb721d11d3778d0

This is still in progress, but most of the ingredients are there.  What looks best is to use P^4 to iterate through the register, and to use the length to distinguish a fast path for ASCII, with lazy evaluation of multibyte structures.  There are a lot of possibilities for mixing in validation, and a possibility of doing UTF-16 as well as 32.  

I added the shuffle table last and realized it has opposite endianness, so a new table will be next.

**Comment by lemire** [comment]
+1

**Comment by KWillets** [comment]
I started a repo for this:  https://github.com/KWillets/fastdecode-utf-8 .  I've built it out to the point where it can iterate through a buffer, etc., but no particular performance tuning.

Happy New Year!

**Comment by lemire** [comment]
Fantastic. On my todo.

**Comment by KWillets** [comment]
I put in a benchmark and got ~2.5 cycles/input byte (64k input).  It still has a bug in consuming the last few bytes of the input, but I think it's doing the work.  

It's faster on wide characters, even with the extra instructions, because more bytes are consumed per loop.  For 3-byte sequences it's around 2 cycles/byte.

**Comment by KWillets** [comment]
The bug in benchmark is fixed now -- it was populating wrong; the original decode was correct.

**Comment by lemire** [comment]
@KWillets I would expect a fast special path for ASCII to be fastest, despite eating fewer bytes per character. Is that not correct?

**Comment by KWillets** [comment]
It's a bit difficult to analyze, due to branches and loops with different instruction counts.  The ASCII path consumes 4 bytes per loop, but gets 4 loops out of each register.  The multibyte path has a one-time setup, followed by a slightly longer shuffle loop, and it does proportionately fewer loops, but each loop consumes more input (eg 12 bytes in one iteration). 

I tried to reduce the branchiness over the weekend, but it ended up slower, so I think I need to understand the current method more.  I may also be tipping the branch predictor too much with my simplistic tests.

**Comment by jerch** [comment]
Great stuff! I wonder your how benchmarks compare to Bob Steagall's SSE based decoder, he was able to speedup things several times (not sure about the cycles per byte). You can find his code here: https://github.com/BobSteagall/utf_utils.

**Comment by lemire** [comment]
@jerch  Thanks for the link.

**Comment by lgqhaoyue** [comment]
great job！How to use this to decode my utf8 string

**Comment by lemire** [comment]
Solved: https://github.com/simdutf/simdutf
