### ISSUE TITLE
Non-SIMD ASCII validation

### ISSUE THREAD

**Issue by pitrou** [lemire/fastvalidate-utf-8#15]
ASCII validation can be almost as fast with a non-SIMD version:

```c
static bool validate_ascii_fast(const char *src, size_t len) {
  const char* end = src + len;
  uint64_t mask1 = 0, mask2 = 0, mask3 = 0, mask4 = 0;

  for (; src < end - 32; src += 32) {
    const uint64_t* p = (const uint64_t*) src;
    mask1 |= p[0];
    mask2 |= p[1];
    mask3 |= p[2];
    mask4 |= p[3];
  }
  for (; src < end - 8; src += 8) {
    const uint64_t* p = (const uint64_t*) src;
    mask1 |= p[0];
  }
  uint8_t tail_mask = 0;
  for (; src < end; src++) {
    tail_mask |= * (const uint8_t*) src;
  }
  uint64_t final_mask = mask1 | mask2 | mask3 | mask4 | tail_mask;
  return !(final_mask & 0x8080808080808080);
}
```

I get ~0.08 cycles per operation here, on a Ryzen 7 CPU with gcc 7.3.0.

**Comment by lemire** [comment]
We need to define what we mean by "non-SIMD". You can disable SIMD in C code using "__attribute__((optimize("no-tree-vectorize")))" under GCC. I call that validate_ascii_nosimd. Then we can use the approach you preconise, as-is, then the compiler will surely vectorize and thus use SIMD. Or you can compare with a hand-rolled SIMD approach with intrinsics.

It is certainly the case that the compiler can come close to what we can do by hand in this case. It might even beat us (depending on your compiler and how much time you spend tuning).

However, I don't think it is true that you can match the SIMD instructions without SIMD instructions in this case, not on current x64 processors. I


```
validate_ascii_fast_avx(data, N)                            	:  0.049 cycles per operation (best) 	0.074 cycles per operation (avg)
validate_ascii_nosimd(data, N)                              	:  0.105 cycles per operation (best) 	0.105 cycles per operation (avg)
validate_ascii_nointrin(data, N)                            	:  0.067 cycles per operation (best) 	0.093 cycles per operation (avg)
```
