### ISSUE TITLE
Dual Apache-2.0 or MIT license?

### ISSUE THREAD

**Issue by ArniDagur** [lemire/fastvalidate-utf-8#20]
I have a WIP [port][1] of this library in Rust, with the potential goal of using it to validate the standard library string type (if it fares well in benchmarks). One potential issue with that however, is that Rust and its standard library are dual licensed under terms of the MIT or Apache-2.0 licenses. This library, however, is only licensed under the Apache-2.0 license. Would it be fine for me to license my crate, which is a derivative work of your library, under a dual "MIT or Apache-2.0" license?

[1]: https://github.com/ArniDagur/rust-isutf8

**Comment by lemire** [comment]
This is fine, we can dual license.

**Comment by lemire** [comment]
If you'd like, you can just issue a PR to this repo, adding the MIT license, and I will approve it.
