### ISSUE TITLE
Boost Software License?

### ISSUE THREAD

**Issue by vinniefalco** [lemire/fastvalidate-utf-8#22]
Apache isn't quite as permissive as the Boost Software License, would you consider re-licensing or dual-licensing this code under the Boost Software License? https://www.boost.org/users/license.html

DIfferences between Boost and Apache

http://www.crystalclearsoftware.com/cgi-bin/boost_wiki/wiki.pl?Boost_License/Apache_Software_License

**Comment by lemire** [comment]
That should be no problem. Can you issue a PR?
