### ISSUE TITLE
hoehrmann algorithms

### ISSUE THREAD

**Issue by mortzdk** [lemire/fastvalidate-utf-8#24]
Hi,

I'm trying to use your different implementations as substitutes depending on the architecture of the machine to validate ut8 strings from websocket frames. If intrinsics is not a possibility, I want to fallback to the fastest available implementation.

I've tried to use all the different implementations from hoehrmann.h, but they all seem to fail several test cases of the [autobahn websocket testsuite](https://github.com/crossbario/autobahn-testsuite/tree/master/autobahntestsuite/autobahntestsuite/case) (section 6)

validate_dfa_utf8_branchless: 6.6.1, 6.6.3, 6.6.4, 6.6.6, 6.6.8, 6.6.10, 6.14.6, 6.14.7
validate_dfa_utf8: 6.6.1, 6.6.3, 6.6.4, 6.6.6, 6.6.8, 6.6.10, 6.14.6, 6.14.7
validate_dfa_utf8_double: 6.6.1, 6.6.3, 6.6.4, 6.6.6, 6.6.8, 6.6.10, 6.7.2, 6.7.4, 6.11.2, 6.14.6, 6.14.7
shiftless_validate_dfa_utf8_double: 6.6.1, 6.6.3, 6.6.4, 6.6.6, 6.6.8, 6.6.10, 6.11.2, 6.14.6, 6.14.7
shiftless_validate_dfa_utf8: 6.6.1, 6.6.3, 6.6.4, 6.6.6, 6.6.8, 6.6.10, 6.14.6, 6.14.7
shiftless_validate_dfa_utf8_branchless: 6.6.1, 6.6.3, 6.6.4, 6.6.6, 6.6.8, 6.6.10, 6.14.6, 6.14.7

validate_utf8, validate_utf8_fast and validate_utf8_fast_avx passes all test in section 6.

These are the test cases, that can be used to test the above things in your tests/unit.c file:
```c
char *goodsequences[] = {"a",                                       
                            "\xc3\xb1",                                          
                            "\xe2\x82\xa1",                                      
                            "\xf0\x90\x8c\xbc",                                  
                            "안녕하세요, 세상",                                  
                            "\xc2\x80", // 6.7.2                                 
                            "\xf0\x90\x80\x80", // 6.7.4                         
                            "\xee\x80\x80" // 6.11.2                             
                           };                                                    
char *badsequences[] = {"\xc3\x28",         // 0                              
                            "\xa0\xa1",         // 1                              
                            "\xe2\x28\xa1",     // 2                              
                            "\xe2\x82\x28",     // 3                              
                            "\xf0\x28\x8c\xbc", // 4                              
                            "\xf0\x90\x28\xbc", // 5                              
                            "\xf0\x28\x8c\x28", // 6                              
                            "\xc0\x9f",         // 7                              
                            "\xf5\xff\xff\xff", // 8                              
                            "\xed\xa0\x81", // 9                                  
                            "\xf8\x90\x80\x80\x80", //10                          
                            "123456789012345\xed", //11                           
                            "123456789012345\xf1", //12                           
                            "123456789012345\xc2", //13                           
                           "\xC2\x7F", // 14                                     
                           "\xce", // 6.6.1                                      
                           "\xce\xba\xe1", // 6.6.3                              
                           "\xce\xba\xe1\xbd", // 6.6.4                          
                           "\xce\xba\xe1\xbd\xb9\xcf", // 6.6.6                  
                           "\xce\xba\xe1\xbd\xb9\xcf\x83\xce", // 6.6.8          
                           "\xce\xba\xe1\xbd\xb9\xcf\x83\xce\xbc\xce", // 6.6.10 
                           "\xdf", // 6.14.6                                     
                           "\xef\xbf", // 6.14.7                                 
                          };
```
This pretty much invalidates the performance measures of those  algorithms, as they seem to be incorrect.

**Comment by abelbraaksma** [comment]
I don't have an answer for you, but maybe you can make the code more readable by placing it into a code block (you can edit the original post). I.e.,use three backticks, optionally followed by a token to indicate the language, which will give you syntax highlighting:

    ```c++
    // your code here
    ```

That would render like this:

```c++
These are the test cases:
char *goodsequences[] = {
   "a", 
   "\xc3\xb1",
   "\xe2\x82\xa1", 
   "\xf0\x90\x8c\xbc",...} 
```

**Comment by mortzdk** [comment]
@abelbraaksma thanks for the advice.

**Comment by lemire** [comment]
I will have a look.

**Comment by lemire** [comment]
Thank you for the new strings for testing.

- You report problems with the DFA schemes that we use as part of the benchmarking tool (but not a part of the library). They are schemes designed and published by Bjoern Hoehrmann, see the header file for credit and reference.
- I have added tests, and Hoehrmann's functions work as expected. The one exception are the "double" schemes which do not work (nor did I really expected them to), they are an experiment of my friend Travis Downs. They could be made to work given some extra work (pull request invited!)... For the time being,  I have added warnings both in the source code and in the benchmark executable regarding the "double" schemes (validate_dfa_utf8_double, shiftless_validate_dfa_utf8_double).



See this PR were the tests were added 

https://github.com/lemire/fastvalidate-utf-8/commit/c5fc4b4c0503f290bfb8604d3e098039850ba18b


> This pretty much invalidates the performance measures of those algorithms, as they seem to be incorrect.

I think that they work as expected. The performance measures are valid, I believe.

I am going to close this, if you have any more issue, please re-open.

**Comment by mortzdk** [comment]
Hi @lemire,

You welcome, thanks for this awesome library.

- I noticed that they were not part of the library after submitting the issue. Thanks for taking your time investigating nonetheless.

- Nice with the extra tests. I have one question: For all other validation algorithms you use the `goodsequences`/`badsequences` and the `len`. But for the Hoehrmann algorithms you use `len+1` is this deliberate? If I change to `len`, the algorithms fail multiple of the `badsequences`. If this is intentional could you please elaborate and close this issue again.

The performance measures of the library algorithms are valid, but comparing those to performances of incorrect algorithms does not make sense in my mind.

**Comment by lemire** [comment]
>  I guess your old blog post actually do compare with the Hoehrmann algorithms.

Yes.... also we do so in the code. I don't understand this comment.

**Comment by lemire** [comment]
> If this is intentional could you please elaborate on why?

The upstream algorithm assumes null-terminated strings.

But that's irrelevant if you just want to benchmark their speed.

> The performance measures of the library algorithms are valid, but comparing those to performances of incorrect algorithms does not make sense in my mind.

You mean for the "_double" schemes? As I demonstrated, the other algorithms are correct. Regarding the "_double" schemes, it is based on domain knowledge: if I had plenty of time, I would fix them up so that they are correct without performance penalty. Note that I did not write them, they were contributions. I might fix them in the future, or maybe you could fix them and issue a PR?

I am not very interested in spending time on these schemes given that we know how to go much faster. And that was the whole point of the demonstration I wanted to make.

> I am not able to reopen this issue by the way.

You should be able to open a new issue.

**Comment by lemire** [comment]
Let me be clearer: the whole purpose of the current library is to show that we can validate UTF-8 quickly, using SIMD instructions.

What does quickly means? Well, we have to compare against *something*. And so I use Hoehrmann's algorithm as a baseline.

We don't even need our Hoehrmann functions to be correct, we just need them to run at the same speed as the correct version. They are a performance baseline.

The conclusion here is "don't use Hoehrmann functions", you can do much better.
