### ISSUE TITLE
out of bound pointer error

### ISSUE THREAD

**Issue by dududuguo** [lemire/fastvalidate-utf-8#27]
Error: memory error: out of bound pointer
File: benchmarks/benchmark.c
Line: 39

void populate(char *data, size_t N) {
  for (size_t i = 0; i < N; i++)
    data[i] = rand() & 0x7f;
  // out of bound pointer error
  data[N] = '\0';
}

**Comment by lemire** [comment]
This library is obsolete. Please use simdutf. See README.
