### ISSUE TITLE
Faster version of reference decoder

### ISSUE THREAD

**Issue by hoehrmann** [lemire/fastvalidate-utf-8#5]
Interesting work!

Note that at the end of https://bjoern.hoehrmann.de/utf-8/decoder/dfa/#variations there is an improved variant of my decoder that saves a shift per byte that might make a better point of comparison.

**Comment by lemire** [comment]
Thanks. I read the full article and I thought using that version but I went with the original on the assumption that the difference would be small. Note that this library does not include your code...

Make sure to read my original blog posts...

https://lemire.me/blog/2018/05/09/how-quickly-can-you-check-that-a-string-is-valid-unicode-utf-8/

https://lemire.me/blog/2018/05/16/validating-utf-8-strings-using-as-little-as-0-7-cycles-per-byte/

The code from my posts is in a separate repo:

https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/tree/master/2018/05/15

I think we could make your original code faster but my point is that your code is far from silly. It is not obvious that one can do much better. Of course, we do here but using instructions you are not using.

**Comment by hoehrmann** [comment]
I tried the code at https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/tree/master/2018/05/08 on an i3-7100U and get avg ~7 cycles for validate_utf8_branchless, and when I put in the faster version, I get avg ~6 cycles, according to the program. When I compile with `clang 7.0.0-3~ubuntu0.18.04.1` instead of system `cc`, it is down to ~5 cycles for the 80 and 512 buffer.

**Comment by lemire** [comment]
I have implemented your shiftless version (now available in my other repo). It is indeed a bit faster.

I am going to close this issue.

I will continue to work on this problem, and I will also continue citing you.
