### ISSUE TITLE
Check all 5 bits in hibits

### ISSUE THREAD

**Issue by KWillets** [lemire/fastvalidate-utf-8#8]
Our original version does table lookups based on the bits [4:7], but the 4-byte sequence requires checking [3:7], ie a 0 in bit 3.  We currently fudge this.

We can check all 5 bits by first splitting ascii/non-ascii on bit 7 (> 0), then assigning continuation lengths etc. to non-ascii elements via pshufb on bits [3:6].  The lookup tables for the various checks have to be shifted, and the input hibits has to have ascii masked out, but we should be able to produce the same outputs.

The ascii mask can also be used to shortcut the multibyte checks.

**Comment by KWillets** [comment]
I should say we may be catching them further on in range checks -- I'll look at the tests.

**Comment by lemire** [comment]
I'm currently exploring other optimizations and I'd like to make sure we have sane tests. (I know that they are minimal...)

**Comment by KWillets** [comment]
It does catch this as a badsequence:  "\xf8\x90\x80\x80\x80".  That is I believe the smallest possible sequence of this type.

**Comment by lemire** [comment]
I am going to close this. Reopen if you disagree.
